"""add events

Revision ID: e79180543be3
Revises: da7101d2aa9c
Create Date: 2019-06-17 10:46:49.526769

"""
import sqlalchemy as sa
from sqlalchemy.dialects.sqlite import INTEGER, TEXT, BOOLEAN, FLOAT, DATETIME

from alembic import op

# revision identifiers, used by Alembic.
revision = 'e79180543be3'
down_revision = 'da7101d2aa9c'
branch_labels = None
depends_on = None


def upgrade():
    event_enum_table = op.create_table('EventEnum',
                                    sa.Column('id', INTEGER, autoincrement=True, primary_key=True),
                                    sa.Column('reasoning', TEXT),
                                    sa.Column('number', INTEGER),
                                    sa.Column('weight', INTEGER),
                                    sa.Column('status', INTEGER),
                                    sa.Column('category', TEXT),
                                    sa.Column('is_cloud_display', BOOLEAN),
                                    sa.Column('description', TEXT),
                                    sa.Column('is_log', BOOLEAN)
                                    )

    data_arr = [{'reasoning': 'ID_UTILITY_FAILURE', 'number': 0, 'weight': 90, 'status': 1, 'category': 'I', 'is_cloud_display': 1,'description': 'Utility power failed, transfer to backup mode','is_log': 1},
                {'reasoning': 'ID_UTILITY_FAILURE_RESTORE', 'number': 1, 'weight': 60, 'status': 0, 'category': 'I', 'is_cloud_display': 1,'description': 'Utility power restored, return from backup mode','is_log': 1},
                {'reasoning': 'ID_AVR_BOOST_ACTIVE', 'number': 2, 'weight': 80, 'status': 1, 'category': 'I', 'is_cloud_display': 1,'description': 'The UPS has enabled boost, low utility voltage','is_log': 1},
                {'reasoning': 'ID_AVR_BUCK_ACTIVE', 'number': 3, 'weight': 80, 'status': 1, 'category': 'I', 'is_cloud_display': 1,'description': 'The UPS has enabled buck, high utility voltage','is_log': 1},
                {'reasoning': 'ID_AVR_BOOST_RESTORE', 'number': 4, 'weight': 1, 'status': 0, 'category': 'I', 'is_cloud_display': 1,'description': 'Output voltage is normal and the voltage boost will stop.','is_log': 1},
                {'reasoning': 'ID_AVR_BUCK_RESTORE', 'number': 5, 'weight': 1, 'status': 0, 'category': 'I', 'is_cloud_display': 1,'description': 'Output voltage is normal and the voltage buck will stop.','is_log': 1},
                {'reasoning': 'ID_UTILITY_TRANSFER_HIGH', 'number': 6, 'weight': 1, 'status': 1, 'category': 'I', 'is_cloud_display': 1,'description': 'Utility power has higher been transfer, battery power will be supplied.','is_log': 1},
                {'reasoning': 'ID_UTILITY_TRANSFER_HIGH_RESTORE', 'number': 7, 'weight': 1, 'status': 0, 'category': 'I', 'is_cloud_display': 1,'description': 'Utility power has been restored; the battery power has stopped supplying power.','is_log': 1},
                {'reasoning': 'ID_UTILITY_TRANSFER_LOW', 'number': 8, 'weight': 1, 'status': 1, 'category': 'I', 'is_cloud_display': 1,'description': 'Utility power has lower been transfer, battery power will be supplied.','is_log': 1},
                {'reasoning': 'ID_UTILITY_TRANSFER_LOW_RESTORE', 'number': 9, 'weight': 1, 'status': 0, 'category': 'I', 'is_cloud_display': 1,'description': 'Utility power has been restored; the battery power has stopped supplying power.','is_log': 1},
                {'reasoning': 'I reversed 10000000000', 'number': 10, 'weight': 1, 'status': None, 'category': 'I', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'I reversed 100000000000', 'number': 11, 'weight': 1, 'status': None, 'category': 'I', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'I reversed 1000000000000', 'number': 12, 'weight': 1, 'status': None, 'category': 'I', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'I reversed 10000000000000', 'number': 13, 'weight': 1, 'status': None, 'category': 'I', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'I reversed 100000000000000', 'number': 14, 'weight': 1, 'status': None, 'category': 'I', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'I reversed 1000000000000000', 'number': 15, 'weight': 1, 'status': None, 'category': 'I', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'ID_UPS_OFF', 'number': 16, 'weight': 90, 'status': 1, 'category': 'O', 'is_cloud_display': 1,'description': 'The UPS has been turned off','is_log': 1},
                {'reasoning': 'ID_UPS_ON', 'number': 17, 'weight': 90, 'status': 0, 'category': 'O', 'is_cloud_display': 1,'description': 'The UPS has been turned on','is_log': 1},
                {'reasoning': 'ID_UPS_SLEEP', 'number': 18, 'weight': 80, 'status': 1, 'category': 'O', 'is_cloud_display': 1,'description': 'The UPS entered sleep mode. Output power will not be provided','is_log': 1},
                {'reasoning': 'ID_UPS_WAKE', 'number': 19, 'weight': 80, 'status': 0, 'category': 'O', 'is_cloud_display': 1,'description': 'The UPS woke up from sleep mode. Output power is being provided','is_log': 1},
                {'reasoning': 'ID_UPS_BYPASS', 'number': 20, 'weight': 1, 'status': 1, 'category': 'O', 'is_cloud_display': 1,'description': 'The UPS enters Bypass Mode','is_log': 1},
                {'reasoning': 'ID_UPS_BYPASS_RESTORE', 'number': 21, 'weight': 1, 'status': 0, 'category': 'O', 'is_cloud_display': 1,'description': 'The UPS leaves Bypass Mode','is_log': 1},
                {'reasoning': 'ID_BYPASS_OVERLAD', 'number': 22, 'weight': 1, 'status': 2, 'category': 'O', 'is_cloud_display': 1,'description': 'The UPS bypass overload','is_log': 1},
                {'reasoning': 'ID_BYPASS_OVERLAD_RESTORE', 'number': 23, 'weight': 1, 'status': 0, 'category': 'O', 'is_cloud_display': 1,'description': 'The UPS bypass overload has been cleared','is_log': 1},
                {'reasoning': 'ID_NCL_ON', 'number': 24, 'weight': 1, 'status': 0, 'category': 'O', 'is_cloud_display': 1,'description': 'Non-Critical bank has been turned on','is_log': 1},
                {'reasoning': 'ID_NCL_OFF', 'number': 25, 'weight': 1, 'status': 1, 'category': 'O', 'is_cloud_display': 1,'description': 'Non-Critical bank has been turned off','is_log': 1},
                {'reasoning': 'ID_ENTER_ECO_MODE', 'number': 26, 'weight': 1, 'status': 1, 'category': 'O', 'is_cloud_display': 1,'description': 'Enters ECO mode','is_log': 1},
                {'reasoning': 'ID_LEAVE_ECO_MODE', 'number': 27, 'weight': 1, 'status': 0, 'category': 'O', 'is_cloud_display': 1,'description': 'Leave ECO mode','is_log': 1},
                {'reasoning': 'ID_OUTPUT_OVERLOAD_RESTORE', 'number': 28, 'weight': 1, 'status': 0, 'category': 'O', 'is_cloud_display': 1,'description': 'Output is no longer overloaded','is_log': 1},
                {'reasoning': 'ID_OUTPUT_STOP_SOON', 'number': 29, 'weight': 1, 'status': 1, 'category': 'O', 'is_cloud_display': 1,'description': 'The output power is going to stop soon','is_log': 1},
                {'reasoning': 'O reversed 100000000000000', 'number': 30, 'weight': 1, 'status': None, 'category': 'O', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'O reversed 1000000000000000', 'number': 31, 'weight': 1, 'status': None, 'category': 'O', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'ID_UPS_OVERLOAD', 'number': 32, 'weight': 90, 'status': 2, 'category': 'U', 'is_cloud_display': 1,'description': 'The UPS has sensed an overload condition','is_log': 1},
                {'reasoning': 'ID_UPS_OVERLOAD_RESTORE', 'number': 33, 'weight': 90, 'status': 0, 'category': 'U', 'is_cloud_display': 1,'description': 'The UPS has returned from an overload condition','is_log': 1},
                {'reasoning': 'ID_TEMP_HIGH', 'number': 34, 'weight': 80, 'status': 1, 'category': 'U', 'is_cloud_display': 1,'description': 'The UPS inner temperature is too high','is_log': 1},
                {'reasoning': 'ID_TEMP_HIGH_RESTORE', 'number': 35, 'weight': 80, 'status': 0, 'category': 'U', 'is_cloud_display': 1,'description': 'The UPS over temperature condition cleared','is_log': 1},
                {'reasoning': 'ID_HARDWARE_FAULT', 'number': 36, 'weight': 90, 'status': 4, 'category': 'U', 'is_cloud_display': 1,'description': 'The UPS hardware fault','is_log': 1},
                {'reasoning': 'ID_ENTER_ECO', 'number': 37, 'weight': 85, 'status': 0, 'category': 'U', 'is_cloud_display': 1,'description': 'The UPS enters ECO mode','is_log': 1},
                {'reasoning': 'ID_LEAVE_ECO', 'number': 38, 'weight': 84, 'status': 0, 'category': 'U', 'is_cloud_display': 1,'description': 'The UPS leaves ECO mode','is_log': 1},
                {'reasoning': 'ID_WIRING_FAULT', 'number': 39, 'weight': 1, 'status': 2, 'category': 'U', 'is_cloud_display': 1,'description': 'The UPS wiring fault has been detected','is_log': 1},
                {'reasoning': 'ID_WIRING_FAULT_RESTORE', 'number': 40, 'weight': 1, 'status': 0, 'category': 'U', 'is_cloud_display': 1,'description': 'The UPS wiring fault has been cleared','is_log': 1},
                {'reasoning': 'ID_FIRMWARE_UPDATE_START', 'number': 41, 'weight': 1, 'status': 0, 'category': 'U', 'is_cloud_display': 1,'description': 'UPS firmware starts to update','is_log': 1},
                {'reasoning': 'ID_FIRMWARE_UPDATE_OVER', 'number': 42, 'weight': 1, 'status': 0, 'category': 'U', 'is_cloud_display': 1,'description': 'UPS firmware update is over','is_log': 1},
                {'reasoning': 'ID_HIGH_POWER_CONSUMPTION', 'number': 43, 'weight': 1, 'status': 1, 'category': 'U', 'is_cloud_display': 1,'description': 'High power consumption','is_log': 1},
                {'reasoning': 'ID_HIGH_POWER_CONSUMPTION_RESTORE', 'number': 44, 'weight': 1, 'status': 0, 'category': 'U', 'is_cloud_display': 1,'description': 'High power consumption restore','is_log': 1},
                {'reasoning': 'ID_LOW_POWER_CONSUMPTION', 'number': 45, 'weight': 1, 'status': 1, 'category': 'U', 'is_cloud_display': 1,'description': 'Low power consumption','is_log': 1},
                {'reasoning': 'ID_LOW_POWER_CONSUMPTION_RESTORE', 'number': 46, 'weight': 1, 'status': 0, 'category': 'U', 'is_cloud_display': 1,'description': 'Low power consumption restore','is_log': 1},
                {'reasoning': 'ID_HARDWARE_STATUS', 'number': 47, 'weight': 1, 'status': 4, 'category': 'U', 'is_cloud_display': 1,'description': 'Hardware Status','is_log': 1},
                {'reasoning': 'ID_BATTERY_LOW', 'number': 48, 'weight': 90, 'status': 1, 'category': 'B', 'is_cloud_display': 1,'description': 'The UPS battery capacity is low than threshold, soon to be exhausted','is_log': 1},
                {'reasoning': 'ID_BATTERY_LOW_RESTORE', 'number': 49, 'weight': 50, 'status': 0, 'category': 'B', 'is_cloud_display': 1,'description': 'The UPS has returned from a low battery condition','is_log': 1},
                {'reasoning': 'ID_BATTERY_ABNORMAL', 'number': 50, 'weight': 90, 'status': 2, 'category': 'B', 'is_cloud_display': 1,'description': 'The battery charger is abnormal','is_log': 1},
                {'reasoning': 'ID_BATTERY_NOT_PRESENT', 'number': 51, 'weight': 90, 'status': 2, 'category': 'B', 'is_cloud_display': 1,'description': 'Battery is not present','is_log': 1},
                {'reasoning': 'ID_BATTERY_NOT_WELL', 'number': 52, 'weight': 89, 'status': 2, 'category': 'B', 'is_cloud_display': 1,'description': 'The battery may not work well anymore','is_log': 1},
                {'reasoning': 'ID_BATTERY_REPLACED', 'number': 53, 'weight': 89, 'status': 0, 'category': 'B', 'is_cloud_display': 1,'description': 'The battery has been replaced','is_log': 1},
                {'reasoning': 'ID_BATTERY_CHARGING_START', 'number': 54, 'weight': 85, 'status': 0, 'category': 'B', 'is_cloud_display': 1,'description': 'Battery is charging','is_log': 1},
                {'reasoning': 'ID_BATTERY_CHARGING_STOP', 'number': 55, 'weight': 1, 'status': 0, 'category': 'B', 'is_cloud_display': 1,'description': 'Battery stopped charging','is_log': 1},
                {'reasoning': 'ID_BATTERY_DISCHARGING_START', 'number': 56, 'weight': 1, 'status': 0, 'category': 'B', 'is_cloud_display': 1,'description': 'Battery is discharging','is_log': 1},
                {'reasoning': 'ID_BATTERY_DISCHARGING_STOP', 'number': 57, 'weight': 1, 'status': 0, 'category': 'B', 'is_cloud_display': 1,'description': 'Battery stopped discharging','is_log': 1},
                {'reasoning': 'ID_AVAILABLE_RUNTIME_IS_INSUFFICIENT', 'number': 58, 'weight': 1, 'status': 1, 'category': 'B', 'is_cloud_display': 1,'description': 'Available runtime is insufficient','is_log': 1},
                {'reasoning': 'ID_BATTERY_CHARGED_FULLY', 'number': 59, 'weight': 1, 'status': 0, 'category': 'B', 'is_cloud_display': 1,'description': 'Battery is fully charged','is_log': 1},
                {'reasoning': 'ID_RUNTIME_EXCEED', 'number': 60, 'weight': 1, 'status': 1, 'category': 'B', 'is_cloud_display': 1,'description': 'Remaining runtime will be exhausted','is_log': 1},
                {'reasoning': 'ID_BATTERY_NOT_PRESENT_RESTORE', 'number': 61, 'weight': 1, 'status': 1, 'category': 'B', 'is_cloud_display': 1,'description': 'Batteries have been installed','is_log': 1},
                {'reasoning': 'ID_BATTERY_CRITICAL_RESTORE', 'number': 62, 'weight': 1, 'status': 0, 'category': 'B', 'is_cloud_display': 1,'description': 'Battery capacity is normal','is_log': 1},
                {'reasoning': 'ID_AVAILABLE_RUNTIME_BECOME_SUFFICIENT', 'number': 63, 'weight': 1, 'status': 1, 'category': 'B', 'is_cloud_display': 1,'description': 'Available runtime become sufficient','is_log': 1},
                {'reasoning': 'ID_BATTERY_TEST_START', 'number': 64, 'weight': 90, 'status': 0, 'category': 'D', 'is_cloud_display': 1,'description': 'The UPS has started a battery test process','is_log': 1},
                {'reasoning': 'ID_BATTERY_TEST_PASS', 'number': 65, 'weight': 60, 'status': 0, 'category': 'D', 'is_cloud_display': 1,'description': 'The UPS battery test passed','is_log': 1},
                {'reasoning': 'ID_BATTERY_TEST_FAIL', 'number': 66, 'weight': 80, 'status': 2, 'category': 'D', 'is_cloud_display': 1,'description': 'The UPS battery test failed','is_log': 1},
                {'reasoning': 'ID_CALIBRATION_START', 'number': 67, 'weight': 80, 'status': 0, 'category': 'D', 'is_cloud_display': 1,'description': 'The UPS has started a runtime calibration process','is_log': 1},
                {'reasoning': 'ID_CALIBRATION_COMPLETE', 'number': 68, 'weight': 1, 'status': 0, 'category': 'D', 'is_cloud_display': 1,'description': 'The UPS runtime calibration completed','is_log': 1},
                {'reasoning': 'ID_CALIBRATION_ABORT', 'number': 69, 'weight': 1, 'status': 1, 'category': 'D', 'is_cloud_display': 1,'description': 'The UPS runtime calibration aborted','is_log': 1},
                {'reasoning': 'ID_BATTERY_TEST_INCOMPLETE', 'number': 70, 'weight': 1, 'status': 1, 'category': 'D', 'is_cloud_display': 1,'description': 'Battery test incomplete','is_log': 1},
                {'reasoning': 'ID_CALIBRATION_INCOMPLETE', 'number': 71, 'weight': 1, 'status': 1, 'category': 'D', 'is_cloud_display': 1,'description': 'Calibration incomplete','is_log': 1},
                {'reasoning': 'D reversed 100000000', 'number': 72, 'weight': 1, 'status': None, 'category': 'D', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'D reversed 1000000000', 'number': 73, 'weight': 1, 'status': None, 'category': 'D', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'D reversed 10000000000', 'number': 74, 'weight': 1, 'status': None, 'category': 'D', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'D reversed 100000000000', 'number': 75, 'weight': 1, 'status': None, 'category': 'D', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'D reversed 1000000000000', 'number': 76, 'weight': 1, 'status': None, 'category': 'D', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'D reversed 10000000000000', 'number': 77, 'weight': 1, 'status': None, 'category': 'D', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'D reversed 100000000000000', 'number': 78, 'weight': 1, 'status': None, 'category': 'D', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'D reversed 1000000000000000', 'number': 79, 'weight': 1, 'status': None, 'category': 'D', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'ID_COMMUNICATION_LOST', 'number': 80, 'weight': 90, 'status': 2, 'category': 'C', 'is_cloud_display': 1,'description': 'Communication with the UPS has been lost','is_log': 1},
                {'reasoning': 'ID_COMMUNICATION_ESTABLISHED', 'number': 81, 'weight': 60, 'status': 0, 'category': 'C', 'is_cloud_display': 1,'description': 'Communication with the UPS has been established','is_log': 1},
                {'reasoning': 'ID_DEVICE_OFFLINE', 'number': 82, 'weight': 80, 'status': 3, 'category': 'C', 'is_cloud_display': 1,'description': 'Device is offline.','is_log': 1},
                {'reasoning': 'ID_DEVICE_ONLINE', 'number': 83, 'weight': 80, 'status': 0, 'category': 'C', 'is_cloud_display': 1,'description': 'Device is online.','is_log': 1},
                {'reasoning': 'ID_COMMUNICATION_CANNOT_ESTABLISH', 'number': 84, 'weight': 1, 'status': 1, 'category': 'C', 'is_cloud_display': 1,'description': 'Communication cannot establish','is_log': 1},
                {'reasoning': 'ID_LOCAL_COMMUNICATION_LOST', 'number': 85, 'weight': 1, 'status': 1, 'category': 'C', 'is_cloud_display': 1,'description': 'Local communication lost','is_log': 1},
                {'reasoning': 'ID_LOCAL_COMMUNICATION_LOST_IN_BATTERY', 'number': 86, 'weight': 1, 'status': 1, 'category': 'C', 'is_cloud_display': 1,'description': 'Local communication lost in a power event','is_log': 1},
                {'reasoning': 'ID_CANNOT_ESTABLISH_NETWORK_COMMUNICATION_WITH_POWER_DEVICE', 'number': 87, 'weight': 1, 'status': 1, 'category': 'C', 'is_cloud_display': 1,'description': 'Cannot establish network communication with Power Device','is_log': 1},
                {'reasoning': 'ID_NETWORK_COMMUNICATION_LOST_WITH_UPS_IN_A_POWER_EVENT', 'number': 88, 'weight': 1, 'status': 1, 'category': 'C', 'is_cloud_display': 1,'description': 'Network communication lost with UPS in a power event','is_log': 1},
                {'reasoning': 'ID_NETWORK_COMMUNICATION_LOST', 'number': 89, 'weight': 1, 'status': 1, 'category': 'C', 'is_cloud_display': 1,'description': 'Network communication lost','is_log': 1},
                {'reasoning': 'ID_COMMUNICATION_IS_ESTABLISHED', 'number': 90, 'weight': 1, 'status': 0, 'category': 'C', 'is_cloud_display': 1,'description': 'Communication is established','is_log': 1},
                {'reasoning': 'ID_LOCAL_COMMUNICATION_LOST_RESTORE', 'number': 91, 'weight': 1, 'status': 0, 'category': 'C', 'is_cloud_display': 1,'description': 'Local communication has resumed','is_log': 1},
                {'reasoning': 'ID_NETWORK_COMMUNICATION_ESTABLISHED_WITH_UPS_PDU_ATS', 'number': 92, 'weight': 1, 'status': 0, 'category': 'C', 'is_cloud_display': 1,'description': 'Network communication established with UPS','is_log': 1},
                {'reasoning': 'ID_NETWORK_COMMUNICATION_IS_RESTORED', 'number': 93, 'weight': 1, 'status': 0, 'category': 'C', 'is_cloud_display': 1,'description': 'Network communication is restored','is_log': 1},
                {'reasoning': 'ID_NETWORK_COMMUNICATION_ESTABLISHED_WITH_POWER_DEVICE', 'number': 94, 'weight': 1, 'status': 0, 'category': 'C', 'is_cloud_display': 1,'description': 'Network communication established with Power Device','is_log': 1},
                {'reasoning': 'C reversed 1000000000000000', 'number': 95, 'weight': 1, 'status': None, 'category': 'C', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'ID_OUTLET_HIGH_POWER_CONSUMPTION', 'number': 96, 'weight': 1, 'status': 1, 'category': 'U1', 'is_cloud_display': 1,'description': 'Outlet high power consumption','is_log': 1},
                {'reasoning': 'ID_OUTLET_HIGH_POWER_CONSUMPTION_RESTORE', 'number': 97, 'weight': 1, 'status': 0, 'category': 'U1', 'is_cloud_display': 1,'description': 'Outlet high power consumption restore','is_log': 1},
                {'reasoning': 'ID_OUTLET_LOW_POWER_CONSUMPTION', 'number': 98, 'weight': 1, 'status': 1, 'category': 'U1', 'is_cloud_display': 1,'description': 'Outlet low power consumption','is_log': 1},
                {'reasoning': 'ID_OUTLET_LOW_POWER_CONSUMPTION_RESTORE', 'number': 99, 'weight': 1, 'status': 0, 'category': 'U1', 'is_cloud_display': 1,'description': 'Outlet low power consumption restore','is_log': 1},
                {'reasoning': 'U1 reversed 10000', 'number': 100, 'weight': 1, 'status': None, 'category': 'U1', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'U1 reversed 100000', 'number': 101, 'weight': 1, 'status': None, 'category': 'U1', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'U1 reversed 1000000', 'number': 102, 'weight': 1, 'status': None, 'category': 'U1', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'U1 reversed 10000000', 'number': 103, 'weight': 1, 'status': None, 'category': 'U1', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'U1 reversed 100000000', 'number': 104, 'weight': 1, 'status': None, 'category': 'U1', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'U1 reversed 1000000000', 'number': 105, 'weight': 1, 'status': None, 'category': 'U1', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'U1 reversed 10000000000', 'number': 106, 'weight': 1, 'status': None, 'category': 'U1', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'U1 reversed 100000000000', 'number': 107, 'weight': 1, 'status': None, 'category': 'U1', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'U1 reversed 1000000000000', 'number': 108, 'weight': 1, 'status': None, 'category': 'U1', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'U1 reversed 10000000000000', 'number': 109, 'weight': 1, 'status': None, 'category': 'U1', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'U1 reversed 100000000000000', 'number': 110, 'weight': 1, 'status': None, 'category': 'U1', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'U1 reversed 1000000000000000', 'number': 111, 'weight': 1, 'status': None, 'category': 'U1', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'ID_RUNTIME_NOT_EXCEED', 'number': 112, 'weight': 1, 'status': 1, 'category': 'B1', 'is_cloud_display': 1,'description': 'Remaining runtime is no longer exhausted','is_log': 1},
                {'reasoning': 'ID_BATTERY_CRITICAL', 'number': 113, 'weight': 1, 'status': 1, 'category': 'B1', 'is_cloud_display': 1,'description': 'Battery capacity is critically low','is_log': 1},
                {'reasoning': 'ID_BATTERY_NEED_REPLACE', 'number': 114, 'weight': 1, 'status': 1, 'category': 'B1', 'is_cloud_display': 1,'description': 'Battery replacement recommended','is_log': 1},
                {'reasoning': 'B1 reversed 1000', 'number': 115, 'weight': 1, 'status': None, 'category': 'B1', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'B1 reversed 10000', 'number': 116, 'weight': 1, 'status': None, 'category': 'B1', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'B1 reversed 100000', 'number': 117, 'weight': 1, 'status': None, 'category': 'B1', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'B1 reversed 1000000', 'number': 118, 'weight': 1, 'status': None, 'category': 'B1', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'B1 reversed 10000000', 'number': 119, 'weight': 1, 'status': None, 'category': 'B1', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'B1 reversed 100000000', 'number': 120, 'weight': 1, 'status': None, 'category': 'B1', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'B1 reversed 1000000000', 'number': 121, 'weight': 1, 'status': None, 'category': 'B1', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'B1 reversed 10000000000', 'number': 122, 'weight': 1, 'status': None, 'category': 'B1', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'B1 reversed 100000000000', 'number': 123, 'weight': 1, 'status': None, 'category': 'B1', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'B1 reversed 1000000000000', 'number': 124, 'weight': 1, 'status': None, 'category': 'B1', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'B1 reversed 10000000000000', 'number': 125, 'weight': 1, 'status': None, 'category': 'B1', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'B1 reversed 100000000000000', 'number': 126, 'weight': 1, 'status': None, 'category': 'B1', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'B1 reversed 1000000000000000', 'number': 127, 'weight': 1, 'status': None, 'category': 'B1', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'ID_SYSTEM_OVERHEAT', 'number': 128, 'weight': 1, 'status': 2, 'category': 'H', 'is_cloud_display': 1,'description': 'System is overheated','is_log': 1},
                {'reasoning': 'ID_OUTPUT_CIRCUIT_SHORT', 'number': 129, 'weight': 1, 'status': 2, 'category': 'H', 'is_cloud_display': 1,'description': 'Output circuit-short','is_log': 1},
                {'reasoning': 'ID_OUTPUT_IS_NO_LONGER_CIRCUIT_SHORTED', 'number': 130, 'weight': 1, 'status': 0, 'category': 'H', 'is_cloud_display': 1,'description': 'Output is no longer circuit-shorted','is_log': 1},
                {'reasoning': 'ID_SITE_WIRING_FAULT', 'number': 131, 'weight': 1, 'status': 2, 'category': 'H', 'is_cloud_display': 1,'description': 'Site wiring fault','is_log': 1},
                {'reasoning': 'ID_HARDWARE_FAULT_RESTORE', 'number': 132, 'weight': 1, 'status': 0, 'category': 'H', 'is_cloud_display': 1,'description': 'UPS is no longer faulty','is_log': 1},
                {'reasoning': 'ID_SYSTEM_OVERHEAT_RESTORE', 'number': 133, 'weight': 1, 'status': 0, 'category': 'H', 'is_cloud_display': 1,'description': 'System is overheated restore','is_log': 1},
                {'reasoning': 'ID_HARDWARE_STATUS_RESTORE', 'number': 134, 'weight': 1, 'status': 0, 'category': 'H', 'is_cloud_display': 1,'description': 'Hardware status restore','is_log': 1},
                {'reasoning': 'H reversed 10000000', 'number': 135, 'weight': 1, 'status': None, 'category': 'H', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'H reversed 100000000', 'number': 136, 'weight': 1, 'status': None, 'category': 'H', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'H reversed 1000000000', 'number': 137, 'weight': 1, 'status': None, 'category': 'H', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'H reversed 10000000000', 'number': 138, 'weight': 1, 'status': None, 'category': 'H', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'H reversed 100000000000', 'number': 139, 'weight': 1, 'status': None, 'category': 'H', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'H reversed 1000000000000', 'number': 140, 'weight': 1, 'status': None, 'category': 'H', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'H reversed 10000000000000', 'number': 141, 'weight': 1, 'status': None, 'category': 'H', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'H reversed 100000000000000', 'number': 142, 'weight': 1, 'status': None, 'category': 'H', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'H reversed 1000000000000000', 'number': 143, 'weight': 1, 'status': None, 'category': 'H', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'ID_SCHEDULE_EXPIRED', 'number': 144, 'weight': 1, 'status': 1, 'category': 'E', 'is_cloud_display': 1,'description': 'A schedule has been initiated, the system will be shutdown.','is_log': 1},
                {'reasoning': 'ID_SHUTDOWN_INITIATED', 'number': 145, 'weight': 1, 'status': 1, 'category': 'E', 'is_cloud_display': 1,'description': 'Shutdown initiated','is_log': 1},
                {'reasoning': 'ID_UPS_IS_BEING_MONITORED', 'number': 146, 'weight': 1, 'status': 0, 'category': 'E', 'is_cloud_display': 1,'description': 'UPS is being monitored','is_log': 1},
                {'reasoning': 'ID_UPS_MONITORING_IS_STOPPED', 'number': 147, 'weight': 1, 'status': 1, 'category': 'E', 'is_cloud_display': 1,'description': 'UPS monitoring is stopped','is_log': 1},
                {'reasoning': 'ID_SHUTDOWN_TIME_IS_INSUFFICIENT', 'number': 148, 'weight': 1, 'status': 1, 'category': 'E', 'is_cloud_display': 1,'description': 'Shutdown time is insufficient','is_log': 1},
                {'reasoning': 'ID_SYSTEM_SHUTDOWN_BY_USER', 'number': 149, 'weight': 1, 'status': 1, 'category': 'E', 'is_cloud_display': 1,'description': 'System shutdown by user','is_log': 1},
                {'reasoning': 'ID_SYSTEM_RESTART_BY_USER', 'number': 150, 'weight': 1, 'status': 1, 'category': 'E', 'is_cloud_display': 1,'description': 'System restart by user','is_log': 1},
                {'reasoning': 'ID_REMOTE_OPERATION_BY_USER', 'number': 151, 'weight': 1, 'status': 1, 'category': 'E', 'is_cloud_display': 1,'description': 'remote operation by user','is_log': 1},
                {'reasoning': 'ID_SHUTDOWN_IS_CANCELED', 'number': 152, 'weight': 1, 'status': 1, 'category': 'E', 'is_cloud_display': 1,'description': 'Shutdown is canceled','is_log': 1},
                {'reasoning': 'ID_SHUTDOWN_TIME_IS_SUFFICIENT', 'number': 153, 'weight': 1, 'status': 1, 'category': 'E', 'is_cloud_display': 1,'description': 'Shutdown time is sufficient','is_log': 1},
                {'reasoning': 'E reversed 10000000000', 'number': 154, 'weight': 1, 'status': None, 'category': 'E', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'E reversed 100000000000', 'number': 155, 'weight': 1, 'status': None, 'category': 'E', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'E reversed 1000000000000', 'number': 156, 'weight': 1, 'status': None, 'category': 'E', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'E reversed 10000000000000', 'number': 157, 'weight': 1, 'status': None, 'category': 'E', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'E reversed 100000000000000', 'number': 158, 'weight': 1, 'status': None, 'category': 'E', 'is_cloud_display': 0,'description': 'reserved','is_log': 1},
                {'reasoning': 'E reversed 1000000000000000', 'number': 159, 'weight': 1, 'status': None, 'category': 'E', 'is_cloud_display': 0,'description': 'reserved','is_log': 1}
                ]

    op.bulk_insert(event_enum_table, data_arr)

def downgrade():
    op.drop_table('EventEnum')
